language: cpp
env:
    - CXX="g++" os="linux64"
    - CXX="g++" os="linux32"
before_install:
    - "./Travis-before-install.sh $os"
script:
    - "./Travis-script.sh $os"
    - "./Travis-deploy.sh $os"