language: cpp
compiler: CC=gcc
before-install:
    - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
    - sudo apt-get update -qq
    - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
script: make