language: cpp
env:
    - CXX="g++"
    - CXX="g++" target="i386"
before_install:
    - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev g++-4.8 g++-4.8-multilib
    - export CXX="g++-4.8"
script: make